use bevy_ecs::prelude::{Component, Entity};

/// Vampiric lifesteal: heals the entity for a fraction of damage it deals.
///
/// Attach to an attacker. When it deals damage, call `notify_hit(damage)` —
/// this returns the heal amount and records it in `last_leeched` /
/// `just_leeched` for VFX. The caller is responsible for applying the returned
/// amount to the entity's `Health` component.
///
/// Heal amount per hit = `damage * fraction + flat`, clamped to ≥ 0.
/// `source` optionally records the entity the leech came from (an item, aura,
/// or skill) for display purposes.
#[derive(Component, Debug, Clone, PartialEq)]
pub struct Leech {
    /// Fraction of damage dealt returned as healing [0.0, 1.0].
    pub fraction: f32,
    /// Flat heal added on every hit regardless of damage.
    pub flat: f32,
    /// Heal amount from the most recent hit (cleared by `tick`).
    pub last_leeched: f32,
    /// Total lifetime healing generated by this component.
    pub total_leeched: f32,
    /// True on the frame a leech heal fires.
    pub just_leeched: bool,
    /// Optional source entity (skill, item, aura) for UI display.
    pub source: Option<Entity>,
    pub enabled: bool,
}

impl Leech {
    pub fn new(fraction: f32) -> Self {
        Self {
            fraction: fraction.clamp(0.0, 1.0),
            flat: 0.0,
            last_leeched: 0.0,
            total_leeched: 0.0,
            just_leeched: false,
            source: None,
            enabled: true,
        }
    }

    pub fn with_flat(mut self, flat: f32) -> Self {
        self.flat = flat.max(0.0);
        self
    }

    pub fn with_source(mut self, source: Entity) -> Self {
        self.source = Some(source);
        self
    }

    /// Calculate the heal amount for `damage` without recording state.
    pub fn calculate(&self, damage: f32) -> f32 {
        (damage * self.fraction + self.flat).max(0.0)
    }

    /// Record a hit, update tracking state, and return the heal amount.
    /// Returns 0.0 when disabled or the calculated amount is zero.
    pub fn notify_hit(&mut self, damage: f32) -> f32 {
        if !self.enabled {
            return 0.0;
        }

        let amount = self.calculate(damage);
        if amount > 0.0 {
            self.last_leeched = amount;
            self.total_leeched += amount;
            self.just_leeched = true;
        }

        amount
    }

    /// Clear `just_leeched` and `last_leeched`; call once per frame.
    pub fn tick(&mut self, _dt: f32) {
        self.just_leeched = false;
        self.last_leeched = 0.0;
    }
}

impl Default for Leech {
    fn default() -> Self {
        Self::new(0.1)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn notify_hit_returns_fraction_of_damage() {
        let mut l = Leech::new(0.2);
        let healed = l.notify_hit(100.0);
        assert!((healed - 20.0).abs() < 1e-5);
        assert!(l.just_leeched);
        assert!((l.last_leeched - 20.0).abs() < 1e-5);
    }

    #[test]
    fn flat_heal_added_per_hit() {
        let mut l = Leech::new(0.0).with_flat(5.0);
        let healed = l.notify_hit(100.0);
        assert!((healed - 5.0).abs() < 1e-5);
    }

    #[test]
    fn fraction_and_flat_combined() {
        let mut l = Leech::new(0.1).with_flat(2.0);
        let healed = l.notify_hit(50.0);
        // 50 * 0.1 + 2.0 = 7.0
        assert!((healed - 7.0).abs() < 1e-5);
    }

    #[test]
    fn calculate_no_side_effects() {
        let l = Leech::new(0.5);
        let _ = l.calculate(100.0);
        assert!(!l.just_leeched);
        assert!((l.total_leeched).abs() < 1e-5);
    }

    #[test]
    fn tick_clears_flags() {
        let mut l = Leech::new(0.2);
        l.notify_hit(100.0);
        l.tick(0.016);
        assert!(!l.just_leeched);
        assert!((l.last_leeched).abs() < 1e-5);
    }

    #[test]
    fn total_leeched_accumulates() {
        let mut l = Leech::new(0.1);
        l.notify_hit(100.0);
        l.tick(0.016);
        l.notify_hit(200.0);
        // 10 + 20 = 30
        assert!((l.total_leeched - 30.0).abs() < 1e-5);
    }

    #[test]
    fn zero_damage_no_leech_event() {
        let mut l = Leech::new(0.5);
        let healed = l.notify_hit(0.0);
        assert!((healed).abs() < 1e-5);
        assert!(!l.just_leeched);
    }

    #[test]
    fn disabled_returns_zero() {
        let mut l = Leech::new(0.5);
        l.enabled = false;
        let healed = l.notify_hit(100.0);
        assert!((healed).abs() < 1e-5);
        assert!(!l.just_leeched);
    }
}
