pub mod aabb;
pub mod ability;
pub mod ability_slot;
pub mod absorption;
pub mod aggro;
pub mod aim;
pub mod alarm;
pub mod ambient_occlusion;
pub mod amplify;
pub mod anchor;
pub mod angular_velocity;
pub mod animation_player;
pub mod armor;
pub mod attach_point;
pub mod audio_emitter;
pub mod audio_filter;
pub mod aura;
pub mod barrier;
pub mod beacon;
pub mod billboard;
pub mod blaze;
pub mod bleed;
pub mod blind;
pub mod blink;
pub mod bloom;
pub mod bone;
pub mod boon;
pub mod boost;
pub mod breath;
pub mod buff;
pub mod buoyancy;
pub mod burn;
pub mod camera;
pub mod capsule;
pub mod carry;
pub mod character_controller;
pub mod charge;
pub mod charm;
pub mod chromatic_aberration;
pub mod cinder;
pub mod climb;
pub mod clip;
pub mod cloth_body;
pub mod collider;
pub mod color;
pub mod color_grading;
pub mod combat;
pub mod combo;
pub mod concuss;
pub mod confuse;
pub mod constraint;
pub mod cooldown;
pub mod corrosion;
pub mod corrupt;
pub mod cover;
pub mod cripple;
pub mod crosshair;
pub mod crouch;
pub mod crumble;
pub mod crush;
pub mod curse;
pub mod damage;
pub mod damping;
pub mod dash;
pub mod daze;
pub mod debuff;
pub mod decal;
pub mod deflect;
pub mod demoralize;
pub mod depth_of_field;
pub mod destructible;
pub mod dialogue;
pub mod disarm;
pub mod dissolve;
pub mod dodge;
pub mod door;
pub mod douse;
pub mod drain;
pub mod draw;
pub mod drench;
pub mod emissive;
pub mod emote;
pub mod empower;
pub mod enervate;
pub mod entangle;
pub mod environment_map;
pub mod equip;
pub mod exhaustion;
pub mod experience;
pub mod explosion;
pub mod expose;
pub mod external_impulse;
pub mod faction;
pub mod fall;
pub mod fear;
pub mod fervor;
pub mod flare;
pub mod flash;
pub mod flinch;
pub mod flip_book;
pub mod flow;
pub mod fog;
pub mod follow;
pub mod footstep;
pub mod force;
pub mod fracture;
pub mod freeze;
pub mod friction;
pub mod frostbite;
pub mod fuel;
pub mod fuse;
pub mod galvanize;
pub mod ghost;
pub mod glide;
pub mod glitch;
pub mod global_transform;
pub mod grab;
pub mod grace;
pub mod grapple;
pub mod grasp;
pub mod gravity;
pub mod grid_snap;
pub mod ground;
pub mod guard;
pub mod gust;
pub mod haste;
pub mod haze;
pub mod health;
pub mod heat;
pub mod hex;
pub mod hitbox;
pub mod hobble;
pub mod homing;
pub mod hover;
pub mod hunger;
pub mod ignite;
pub mod immune;
pub mod impact;
pub mod input_map;
pub mod interactable;
pub mod intercept;
pub mod interrupt;
pub mod inventory;
pub mod invincible;
pub mod item;
pub mod jeer;
pub mod jetpack;
pub mod joint;
pub mod jolt;
pub mod jump;
pub mod kinematic;
pub mod kneel;
pub mod knockback;
pub mod lacerate;
pub mod lance;
pub mod lash;
pub mod layer;
pub mod ledge;
pub mod leech;
pub mod lens_flare;
pub mod level;
pub mod lifetime;
pub mod light;
pub mod lock;
pub mod lod;
pub mod logging;
pub mod loot_table;
pub mod lunge;
pub mod lure;
pub mod magnet;
pub mod maim;
pub mod malice;
pub mod mana;
pub mod mark;
pub mod mass;
pub mod material;
pub mod melee;
pub mod mesh;
pub mod minimap;
pub mod momentum;
pub mod morph;
pub mod motion_blur;
pub mod mount;
pub mod move_speed;
pub mod muffle;
pub mod name;
pub mod nav_mesh_agent;
pub mod network_id;
pub mod nimble;
pub mod notice;
pub mod npc;
pub mod nullify;
pub mod numb;
pub mod obstacle;
pub mod orbit;
pub mod oscillate;
pub mod outline;
pub mod overflow;
pub mod overheat;
pub mod overload;
pub mod overpower;
pub mod parent;
pub mod parry;
pub mod particle_system;
pub mod patrol;
pub mod petrify;
pub mod phase;
pub mod pickup;
pub mod pierce;
pub mod pivot;
pub mod platform;
pub mod plunge;
pub mod poison;
pub mod portal;
pub mod pounce;
pub mod power;
pub mod projectile;
pub mod prone;
pub mod provoke;
pub mod prowl;
pub mod pulse;
pub mod quest;
pub mod radar;
pub mod ragdoll;
pub mod rage;
pub mod rally;
pub mod ray;
pub mod reave;
pub mod recharge;
pub mod recoil;
pub mod reflect;
pub mod reflection_probe;
pub mod regen;
pub mod repel;
pub mod respawn;
pub mod restitution;
pub mod retaliate;
pub mod reveal;
pub mod reverb_zone;
pub mod revive;
pub mod ricochet;
pub mod rigid_body;
pub mod root;
pub mod rope;
pub mod rout;
pub mod save_data;
pub mod scan;
pub mod scatter;
pub mod scorch;
pub mod screen_shake;
pub mod sensor;
pub mod shadow;
pub mod shield;
pub mod shield_break;
pub mod shock;
pub mod shroud;
pub mod silence;
pub mod siphon;
pub mod skeleton;
pub mod skinned_mesh;
pub mod skybox;
pub mod slam;
pub mod slide;
pub mod slow;
pub mod slow_mo;
pub mod smoke;
pub mod snare;
pub mod spawn_point;
pub mod sphere;
pub mod spike;
pub mod spring;
pub mod sprint;
pub mod sprite;
pub mod stagger;
pub mod stamina;
pub mod stat;
pub mod status_effect;
pub mod stealth;
pub mod stun;
pub mod sunder;
pub mod suppress;
pub mod surge;
pub mod swim;
pub mod tag;
pub mod taint;
pub mod tally;
pub mod target;
pub mod taunt;
pub mod tether;
pub mod text;
pub mod thorns;
pub mod time;
pub mod timer;
pub mod tint;
pub mod tone_map;
pub mod trail;
pub mod trample;
pub mod trance;
pub mod transform;
pub mod trap;
pub mod tremble;
pub mod trigger;
pub mod turret;
pub mod tween;
pub mod upgrade;
pub mod velocity;
pub mod venom;
pub mod vex;
pub mod vibrate;
pub mod viewport;
pub mod vignette;
pub mod vigor;
pub mod visible;
pub mod vision;
pub mod volumetric_light;
pub mod wall;
pub mod wane;
pub mod warp;
pub mod water_body;
pub mod wave;
pub mod weaken;
pub mod weather;
pub mod wind;
pub mod wither;
pub mod wound;
pub mod z_index;

pub use aabb::Aabb;
pub use ability::Ability;
pub use ability_slot::{AbilitySlot, Slot};
pub use absorption::Absorption;
pub use aggro::{Aggro, ThreatEntry};
pub use aim::{Aim, AimMode};
pub use alarm::Alarm;
pub use ambient_occlusion::AmbientOcclusion;
pub use amplify::Amplify;
pub use anchor::{Anchor, AnchorPreset};
pub use angular_velocity::AngularVelocity;
pub use animation_player::AnimationPlayer;
pub use armor::{Armor, ArmorType};
pub use attach_point::AttachPoint;
pub use audio_emitter::{AudioEmitter, AudioListener};
pub use audio_filter::{AudioFilter, FilterType};
pub use aura::{Aura, AuraKind};
pub use barrier::Barrier;
pub use beacon::Beacon;
pub use billboard::{Billboard, BillboardMode};
pub use blaze::Blaze;
pub use bleed::Bleed;
pub use blind::Blind;
pub use blink::{Blink, BlinkState};
pub use bloom::Bloom;
pub use bone::Bone;
pub use boon::Boon;
pub use boost::{Boost, BoostStat};
pub use breath::{Breath, BreathState};
pub use buff::{Buff, BuffEntry};
pub use buoyancy::Buoyancy;
pub use burn::Burn;
pub use camera::Camera;
pub use capsule::Capsule;
pub use carry::{Carry, CarryPhase};
pub use character_controller::CharacterController;
pub use charge::{Charge, ChargePhase};
pub use charm::Charm;
pub use chromatic_aberration::ChromaticAberration;
pub use cinder::Cinder;
pub use climb::{Climb, ClimbPhase};
pub use clip::{Clip, ClipState};
pub use cloth_body::ClothBody;
pub use collider::Collider;
pub use color::Color;
pub use color_grading::ColorGrading;
pub use combat::{Combat, CombatStance};
pub use combo::Combo;
pub use concuss::Concuss;
pub use confuse::Confuse;
pub use constraint::{Constraint, ConstraintKind};
pub use cooldown::Cooldown;
pub use corrosion::Corrosion;
pub use corrupt::Corrupt;
pub use cover::Cover;
pub use cripple::Cripple;
pub use crosshair::{Crosshair, CrosshairStyle};
pub use crouch::{Crouch, CrouchPhase};
pub use crumble::Crumble;
pub use crush::Crush;
pub use curse::{Curse, CurseKind};
pub use damage::{Damage, DamageType};
pub use damping::Damping;
pub use dash::{Dash, DashPhase};
pub use daze::Daze;
pub use debuff::{Debuff, DebuffEntry};
pub use decal::Decal;
pub use deflect::Deflect;
pub use demoralize::Demoralize;
pub use depth_of_field::DepthOfField;
pub use destructible::{Destructible, DestructionState};
pub use dialogue::{Dialogue, DialogueLine};
pub use disarm::Disarm;
pub use dissolve::Dissolve;
pub use dodge::{Dodge, DodgePhase};
pub use door::{Door, DoorState};
pub use douse::Douse;
pub use drain::Drain;
pub use draw::{Draw, DrawPhase};
pub use drench::Drench;
pub use emissive::Emissive;
pub use emote::{Emote, EmoteState};
pub use empower::Empower;
pub use enervate::Enervate;
pub use entangle::Entangle;
pub use environment_map::EnvironmentMap;
pub use equip::{Equip, EquipSlot};
pub use exhaustion::Exhaustion;
pub use experience::Experience;
pub use explosion::{Explosion, ExplosionState};
pub use expose::Expose;
pub use external_impulse::ExternalImpulse;
pub use faction::{Faction, FactionRel};
pub use fall::{Fall, FallState};
pub use fear::{Fear, FearState};
pub use fervor::Fervor;
pub use flare::Flare;
pub use flash::{Flash, FlashCurve};
pub use flinch::Flinch;
pub use flip_book::FlipBook;
pub use flow::Flow;
pub use fog::{Fog, FogMode};
pub use follow::{Follow, LookAt};
pub use footstep::{Footstep, SurfaceKind};
pub use force::{Force, ForceEntry, ForceMode};
pub use fracture::Fracture;
pub use freeze::{Freeze, FreezeState};
pub use friction::Friction;
pub use frostbite::Frostbite;
pub use fuel::{Fuel, FuelState};
pub use fuse::Fuse;
pub use galvanize::Galvanize;
pub use ghost::{Ghost, GhostExitMode};
pub use glide::{Glide, GlidePhase};
pub use glitch::Glitch;
pub use global_transform::GlobalTransform;
pub use grab::{Grab, GrabRole};
pub use grace::Grace;
pub use grapple::{Grapple, GrappleState};
pub use grasp::Grasp;
pub use gravity::{Gravity, GravityScale};
pub use grid_snap::GridSnap;
pub use ground::Ground;
pub use guard::{Guard, GuardPhase};
pub use gust::Gust;
pub use haste::{Haste, HasteKind, HasteStack};
pub use haze::Haze;
pub use health::Health;
pub use heat::{Heat, ThermalState};
pub use hex::Hex;
pub use hitbox::{Hitbox, HitboxShape};
pub use hobble::Hobble;
pub use homing::{Homing, HomingMode};
pub use hover::{Hover, HoverMode};
pub use hunger::{Hunger, HungerState};
pub use ignite::Ignite;
pub use immune::Immune;
pub use impact::Impact;
pub use input_map::{Binding, InputCode, InputMap};
pub use interactable::{InteractTrigger, Interactable};
pub use intercept::Intercept;
pub use interrupt::Interrupt;
pub use inventory::Inventory;
pub use invincible::Invincible;
pub use item::{Item, ItemCategory, ItemRarity};
pub use jeer::Jeer;
pub use jetpack::{Jetpack, JetpackState};
pub use joint::{Joint, JointType};
pub use jolt::Jolt;
pub use jump::Jump;
pub use kinematic::Kinematic;
pub use kneel::Kneel;
pub use knockback::{Knockback, KnockbackSource};
pub use lacerate::Lacerate;
pub use lance::Lance;
pub use lash::Lash;
pub use layer::Layer;
pub use ledge::{Ledge, LedgePhase};
pub use leech::Leech;
pub use lens_flare::LensFlare;
pub use level::Level;
pub use lifetime::Lifetime;
pub use light::{DirectionalLight, PointLight, SpotLight};
pub use lock::{Lock, LockState};
pub use lod::{Lod, LodLevel};
pub use logging::init_logging;
pub use loot_table::{LootEntry, LootTable};
pub use lunge::{Lunge, LungePhase};
pub use lure::{Lure, LureState};
pub use magnet::{Magnet, MagnetMode};
pub use maim::Maim;
pub use malice::Malice;
pub use mana::Mana;
pub use mark::{Mark, MarkEntry};
pub use mass::Mass;
pub use material::Material;
pub use melee::{Melee, MeleePhase};
pub use mesh::Mesh;
pub use minimap::Minimap;
pub use momentum::Momentum;
pub use morph::Morph;
pub use motion_blur::MotionBlur;
pub use mount::{Mount, SeatOffset};
pub use move_speed::MoveSpeed;
pub use muffle::Muffle;
pub use name::Name;
pub use nav_mesh_agent::{NavAgentState, NavMeshAgent};
pub use network_id::{NetworkAuthority, NetworkId};
pub use nimble::Nimble;
pub use notice::{Notice, NoticeState};
pub use npc::{Npc, NpcRole, NpcState};
pub use nullify::Nullify;
pub use numb::Numb;
pub use obstacle::{Obstacle, ObstacleShape};
pub use orbit::Orbit;
pub use oscillate::{Oscillate, OscillateAxis};
pub use outline::{Outline, OutlineMode};
pub use overflow::Overflow;
pub use overheat::{Overheat, OverheatState};
pub use overload::Overload;
pub use overpower::Overpower;
pub use parent::Parent;
pub use parry::{Parry, ParryState};
pub use particle_system::{EmissionShape, ParticleSystem};
pub use patrol::{Patrol, PatrolMode};
pub use petrify::Petrify;
pub use phase::Phase;
pub use pickup::{Pickup, PickupEffect};
pub use pierce::Pierce;
pub use pivot::{Pivot, PivotSpace};
pub use platform::{Platform, PlatformMode};
pub use plunge::{Plunge, PlungePhase};
pub use poison::Poison;
pub use portal::Portal;
pub use pounce::Pounce;
pub use power::{Power, PowerRole};
pub use projectile::Projectile;
pub use prone::Prone;
pub use provoke::Provoke;
pub use prowl::Prowl;
pub use pulse::{Pulse, PulseMode};
pub use quest::{Quest, QuestObjective, QuestState};
pub use radar::{Radar, RadarContact, RadarFilter};
pub use ragdoll::{Ragdoll, RagdollMode};
pub use rage::{Rage, RagePhase};
pub use rally::Rally;
pub use ray::Ray;
pub use reave::Reave;
pub use recharge::Recharge;
pub use recoil::Recoil;
pub use reflect::Reflect;
pub use reflection_probe::{ProbeUpdateMode, ReflectionProbe};
pub use regen::{Regen, RegenTarget};
pub use repel::Repel;
pub use respawn::{Respawn, RespawnState};
pub use restitution::Restitution;
pub use retaliate::Retaliate;
pub use reveal::Reveal;
pub use reverb_zone::ReverbZone;
pub use revive::{Revive, ReviveState};
pub use ricochet::Ricochet;
pub use rigid_body::RigidBody;
pub use root::Root;
pub use rope::{Rope, RopeNode};
pub use rout::Rout;
pub use save_data::SaveData;
pub use scan::Scan;
pub use scatter::Scatter;
pub use scorch::Scorch;
pub use screen_shake::ScreenShake;
pub use sensor::{Sensor, SensorShape};
pub use shadow::{Shadow, ShadowFilterMethod};
pub use shield::Shield;
pub use shield_break::ShieldBreak;
pub use shock::Shock;
pub use shroud::Shroud;
pub use silence::Silence;
pub use siphon::Siphon;
pub use skeleton::Skeleton;
pub use skinned_mesh::SkinnedMesh;
pub use skybox::{Skybox, SkyboxProjection};
pub use slam::{Slam, SlamPhase};
pub use slide::{Slide, SlidePhase};
pub use slow::Slow;
pub use slow_mo::{SlowMo, SlowMoSource};
pub use smoke::{Smoke, SmokeStyle};
pub use snare::Snare;
pub use spawn_point::SpawnPoint;
pub use sphere::Sphere;
pub use spike::Spike;
pub use spring::Spring;
pub use sprint::{Sprint, SprintState};
pub use sprite::{Sprite, TextureAtlas};
pub use stagger::{Stagger, StaggerPhase};
pub use stamina::Stamina;
pub use stat::Stat;
pub use status_effect::{EffectKind, StatusEffect};
pub use stealth::{Stealth, Visibility};
pub use stun::{Stun, StunSeverity};
pub use sunder::Sunder;
pub use suppress::Suppress;
pub use surge::Surge;
pub use swim::{Swim, SwimState};
pub use tag::Tag;
pub use taint::Taint;
pub use tally::Tally;
pub use target::{Target, TargetPriority};
pub use taunt::Taunt;
pub use tether::Tether;
pub use text::{Text, TextAlignment};
pub use thorns::Thorns;
pub use time::Time;
pub use timer::Timer;
pub use tint::{Tint, TintMode};
pub use tone_map::{ToneMap, ToneMappingMode};
pub use trail::{Trail, TrailPoint};
pub use trample::Trample;
pub use trance::Trance;
pub use transform::Transform;
pub use trap::{Trap, TrapEffect, TrapState};
pub use tremble::Tremble;
pub use trigger::{Trigger, TriggerEvent};
pub use turret::{FireMode, Turret};
pub use tween::{EasingFn, RepeatMode, Tween, TweenTarget};
pub use upgrade::{Upgrade, UpgradeTier};
pub use velocity::Velocity;
pub use venom::Venom;
pub use vex::Vex;
pub use vibrate::Vibrate;
pub use viewport::Viewport;
pub use vignette::Vignette;
pub use vigor::Vigor;
pub use visible::Visible;
pub use vision::Vision;
pub use volumetric_light::VolumetricLight;
pub use wall::{Wall, WallState};
pub use wane::Wane;
pub use warp::{Warp, WarpPhase};
pub use water_body::WaterBody;
pub use wave::Wave;
pub use weaken::Weaken;
pub use weather::{Precipitation, Weather};
pub use wind::Wind;
pub use wither::Wither;
pub use wound::Wound;
pub use z_index::ZIndex;

pub fn propagate_global_transforms(world: &mut bevy_ecs::world::World) {
    use bevy_ecs::prelude::Entity;
    use glam::Mat4;
    use std::collections::HashMap;

    let mut query = world.query::<(Entity, &Transform, Option<&Parent>)>();
    let entries: Vec<(Entity, Mat4, Option<Entity>)> = query
        .iter(world)
        .map(|(e, t, p)| (e, t.to_matrix(), p.map(|p| p.0)))
        .collect();

    let mut globals: HashMap<Entity, Mat4> =
        entries.iter().map(|(e, local, _)| (*e, *local)).collect();

    for _ in 0..8 {
        for (e, local, parent) in &entries {
            if let Some(parent_e) = parent {
                if let Some(&parent_global) = globals.get(parent_e) {
                    globals.insert(*e, parent_global * *local);
                }
            }
        }
    }

    let mut gt_query = world.query::<(Entity, &mut GlobalTransform)>();
    for (e, mut gt) in gt_query.iter_mut(world) {
        if let Some(&mat) = globals.get(&e) {
            gt.0 = mat;
        }
    }
}
