pub mod aabb;
pub mod ability;
pub mod ability_slot;
pub mod aggro;
pub mod aim;
pub mod ambient_occlusion;
pub mod anchor;
pub mod angular_velocity;
pub mod animation_player;
pub mod attach_point;
pub mod audio_emitter;
pub mod audio_filter;
pub mod billboard;
pub mod blink;
pub mod bloom;
pub mod bone;
pub mod boost;
pub mod buoyancy;
pub mod camera;
pub mod capsule;
pub mod character_controller;
pub mod chromatic_aberration;
pub mod cloth_body;
pub mod collider;
pub mod color;
pub mod color_grading;
pub mod combat;
pub mod constraint;
pub mod cooldown;
pub mod crosshair;
pub mod crouch;
pub mod damage;
pub mod damping;
pub mod dash;
pub mod decal;
pub mod depth_of_field;
pub mod destructible;
pub mod dialogue;
pub mod dissolve;
pub mod door;
pub mod emissive;
pub mod emote;
pub mod environment_map;
pub mod experience;
pub mod external_impulse;
pub mod faction;
pub mod flip_book;
pub mod fog;
pub mod follow;
pub mod footstep;
pub mod friction;
pub mod global_transform;
pub mod grapple;
pub mod gravity;
pub mod grid_snap;
pub mod ground;
pub mod health;
pub mod hitbox;
pub mod homing;
pub mod input_map;
pub mod interactable;
pub mod inventory;
pub mod item;
pub mod joint;
pub mod jump;
pub mod knockback;
pub mod layer;
pub mod ledge;
pub mod lens_flare;
pub mod lifetime;
pub mod light;
pub mod lod;
pub mod logging;
pub mod loot_table;
pub mod mass;
pub mod material;
pub mod mesh;
pub mod minimap;
pub mod motion_blur;
pub mod mount;
pub mod name;
pub mod nav_mesh_agent;
pub mod network_id;
pub mod npc;
pub mod outline;
pub mod parent;
pub mod particle_system;
pub mod patrol;
pub mod pickup;
pub mod portal;
pub mod projectile;
pub mod quest;
pub mod radar;
pub mod ragdoll;
pub mod ray;
pub mod reflection_probe;
pub mod respawn;
pub mod restitution;
pub mod reverb_zone;
pub mod rigid_body;
pub mod save_data;
pub mod screen_shake;
pub mod sensor;
pub mod shadow;
pub mod shield;
pub mod skeleton;
pub mod skinned_mesh;
pub mod skybox;
pub mod smoke;
pub mod spawn_point;
pub mod sphere;
pub mod spring;
pub mod sprite;
pub mod stat;
pub mod status_effect;
pub mod stealth;
pub mod tag;
pub mod target;
pub mod text;
pub mod time;
pub mod timer;
pub mod tone_map;
pub mod trail;
pub mod transform;
pub mod trap;
pub mod trigger;
pub mod turret;
pub mod tween;
pub mod velocity;
pub mod viewport;
pub mod vignette;
pub mod visible;
pub mod volumetric_light;
pub mod water_body;
pub mod weather;
pub mod wind;
pub mod z_index;

pub use aabb::Aabb;
pub use ability::Ability;
pub use ability_slot::{AbilitySlot, Slot};
pub use aggro::{Aggro, ThreatEntry};
pub use aim::{Aim, AimMode};
pub use ambient_occlusion::AmbientOcclusion;
pub use anchor::{Anchor, AnchorPreset};
pub use angular_velocity::AngularVelocity;
pub use animation_player::AnimationPlayer;
pub use attach_point::AttachPoint;
pub use audio_emitter::{AudioEmitter, AudioListener};
pub use audio_filter::{AudioFilter, FilterType};
pub use billboard::{Billboard, BillboardMode};
pub use blink::{Blink, BlinkState};
pub use bloom::Bloom;
pub use bone::Bone;
pub use boost::{Boost, BoostStat};
pub use buoyancy::Buoyancy;
pub use camera::Camera;
pub use capsule::Capsule;
pub use character_controller::CharacterController;
pub use chromatic_aberration::ChromaticAberration;
pub use cloth_body::ClothBody;
pub use collider::Collider;
pub use color::Color;
pub use color_grading::ColorGrading;
pub use combat::{Combat, CombatStance};
pub use constraint::{Constraint, ConstraintKind};
pub use cooldown::Cooldown;
pub use crosshair::{Crosshair, CrosshairStyle};
pub use crouch::{Crouch, CrouchPhase};
pub use damage::{Damage, DamageType};
pub use damping::Damping;
pub use dash::{Dash, DashPhase};
pub use decal::Decal;
pub use depth_of_field::DepthOfField;
pub use destructible::{Destructible, DestructionState};
pub use dialogue::{Dialogue, DialogueLine};
pub use dissolve::Dissolve;
pub use door::{Door, DoorState};
pub use emissive::Emissive;
pub use emote::{Emote, EmoteState};
pub use environment_map::EnvironmentMap;
pub use experience::Experience;
pub use external_impulse::ExternalImpulse;
pub use faction::{Faction, FactionRel};
pub use flip_book::FlipBook;
pub use fog::{Fog, FogMode};
pub use follow::{Follow, LookAt};
pub use footstep::{Footstep, SurfaceKind};
pub use friction::Friction;
pub use global_transform::GlobalTransform;
pub use grapple::{Grapple, GrappleState};
pub use gravity::{Gravity, GravityScale};
pub use grid_snap::GridSnap;
pub use ground::Ground;
pub use health::Health;
pub use hitbox::{Hitbox, HitboxShape};
pub use homing::{Homing, HomingMode};
pub use input_map::{Binding, InputCode, InputMap};
pub use interactable::{InteractTrigger, Interactable};
pub use inventory::Inventory;
pub use item::{Item, ItemCategory, ItemRarity};
pub use joint::{Joint, JointType};
pub use jump::Jump;
pub use knockback::{Knockback, KnockbackSource};
pub use layer::Layer;
pub use ledge::{Ledge, LedgePhase};
pub use lens_flare::LensFlare;
pub use lifetime::Lifetime;
pub use light::{DirectionalLight, PointLight, SpotLight};
pub use lod::{Lod, LodLevel};
pub use logging::init_logging;
pub use loot_table::{LootEntry, LootTable};
pub use mass::Mass;
pub use material::Material;
pub use mesh::Mesh;
pub use minimap::Minimap;
pub use motion_blur::MotionBlur;
pub use mount::{Mount, SeatOffset};
pub use name::Name;
pub use nav_mesh_agent::{NavAgentState, NavMeshAgent};
pub use network_id::{NetworkAuthority, NetworkId};
pub use npc::{Npc, NpcRole, NpcState};
pub use outline::{Outline, OutlineMode};
pub use parent::Parent;
pub use particle_system::{EmissionShape, ParticleSystem};
pub use patrol::{Patrol, PatrolMode};
pub use pickup::{Pickup, PickupEffect};
pub use portal::Portal;
pub use projectile::Projectile;
pub use quest::{Quest, QuestObjective, QuestState};
pub use radar::{Radar, RadarContact, RadarFilter};
pub use ragdoll::{Ragdoll, RagdollMode};
pub use ray::Ray;
pub use reflection_probe::{ProbeUpdateMode, ReflectionProbe};
pub use respawn::{Respawn, RespawnState};
pub use restitution::Restitution;
pub use reverb_zone::ReverbZone;
pub use rigid_body::RigidBody;
pub use save_data::SaveData;
pub use screen_shake::ScreenShake;
pub use sensor::{Sensor, SensorShape};
pub use shadow::{Shadow, ShadowFilterMethod};
pub use shield::Shield;
pub use skeleton::Skeleton;
pub use skinned_mesh::SkinnedMesh;
pub use skybox::{Skybox, SkyboxProjection};
pub use smoke::{Smoke, SmokeStyle};
pub use spawn_point::SpawnPoint;
pub use sphere::Sphere;
pub use spring::Spring;
pub use sprite::{Sprite, TextureAtlas};
pub use stat::Stat;
pub use status_effect::{EffectKind, StatusEffect};
pub use stealth::{Stealth, Visibility};
pub use tag::Tag;
pub use target::{Target, TargetPriority};
pub use text::{Text, TextAlignment};
pub use time::Time;
pub use timer::Timer;
pub use tone_map::{ToneMap, ToneMappingMode};
pub use trail::{Trail, TrailPoint};
pub use transform::Transform;
pub use trap::{Trap, TrapEffect, TrapState};
pub use trigger::{Trigger, TriggerEvent};
pub use turret::{FireMode, Turret};
pub use tween::{EasingFn, RepeatMode, Tween, TweenTarget};
pub use velocity::Velocity;
pub use viewport::Viewport;
pub use vignette::Vignette;
pub use visible::Visible;
pub use volumetric_light::VolumetricLight;
pub use water_body::WaterBody;
pub use weather::{Precipitation, Weather};
pub use wind::Wind;
pub use z_index::ZIndex;

pub fn propagate_global_transforms(world: &mut bevy_ecs::world::World) {
    use bevy_ecs::prelude::Entity;
    use glam::Mat4;
    use std::collections::HashMap;

    let mut query = world.query::<(Entity, &Transform, Option<&Parent>)>();
    let entries: Vec<(Entity, Mat4, Option<Entity>)> = query
        .iter(world)
        .map(|(e, t, p)| (e, t.to_matrix(), p.map(|p| p.0)))
        .collect();

    let mut globals: HashMap<Entity, Mat4> =
        entries.iter().map(|(e, local, _)| (*e, *local)).collect();

    for _ in 0..8 {
        for (e, local, parent) in &entries {
            if let Some(parent_e) = parent {
                if let Some(&parent_global) = globals.get(parent_e) {
                    globals.insert(*e, parent_global * *local);
                }
            }
        }
    }

    let mut gt_query = world.query::<(Entity, &mut GlobalTransform)>();
    for (e, mut gt) in gt_query.iter_mut(world) {
        if let Some(&mat) = globals.get(&e) {
            gt.0 = mat;
        }
    }
}
