pub mod aabb;
pub mod ability;
pub mod ability_slot;
pub mod absorption;
pub mod aggro;
pub mod aim;
pub mod alarm;
pub mod ambient_occlusion;
pub mod ammo;
pub mod amplify;
pub mod anchor;
pub mod angular_velocity;
pub mod animation_player;
pub mod armor;
pub mod attach_point;
pub mod audio_emitter;
pub mod audio_filter;
pub mod aura;
pub mod avenge;
pub mod barrier;
pub mod beacon;
pub mod billboard;
pub mod blaze;
pub mod bleed;
pub mod blind;
pub mod blink;
pub mod bloom;
pub mod bone;
pub mod boon;
pub mod boost;
pub mod breath;
pub mod buff;
pub mod bulk;
pub mod buoyancy;
pub mod burn;
pub mod camera;
pub mod camouflage;
pub mod capsule;
pub mod carry;
pub mod character_controller;
pub mod charge;
pub mod charm;
pub mod chill;
pub mod chromatic_aberration;
pub mod cinder;
pub mod climb;
pub mod cling;
pub mod clip;
pub mod cloth_body;
pub mod collider;
pub mod color;
pub mod color_grading;
pub mod combat;
pub mod combo;
pub mod concuss;
pub mod confuse;
pub mod constraint;
pub mod cooldown;
pub mod corrosion;
pub mod corrupt;
pub mod counter;
pub mod cover;
pub mod cripple;
pub mod crosshair;
pub mod crouch;
pub mod crumble;
pub mod crunch;
pub mod crush;
pub mod curse;
pub mod damage;
pub mod damping;
pub mod dash;
pub mod daze;
pub mod debuff;
pub mod decal;
pub mod deflect;
pub mod demoralize;
pub mod depth_of_field;
pub mod destructible;
pub mod dialogue;
pub mod disarm;
pub mod dissolve;
pub mod dodge;
pub mod doom;
pub mod door;
pub mod douse;
pub mod drain;
pub mod draw;
pub mod dread;
pub mod drench;
pub mod echo;
pub mod edge;
pub mod emissive;
pub mod emote;
pub mod empower;
pub mod enervate;
pub mod enlarge;
pub mod entangle;
pub mod environment_map;
pub mod equip;
pub mod exhaustion;
pub mod exile;
pub mod experience;
pub mod explosion;
pub mod expose;
pub mod external_impulse;
pub mod faction;
pub mod fall;
pub mod faze;
pub mod fear;
pub mod feint;
pub mod fend;
pub mod feral;
pub mod fervor;
pub mod flare;
pub mod flash;
pub mod flinch;
pub mod flip_book;
pub mod flow;
pub mod fog;
pub mod follow;
pub mod footstep;
pub mod force;
pub mod fracture;
pub mod freeze;
pub mod friction;
pub mod frostbite;
pub mod fuel;
pub mod fury;
pub mod fuse;
pub mod galvanize;
pub mod ghost;
pub mod glide;
pub mod glimmer;
pub mod glitch;
pub mod global_transform;
pub mod goad;
pub mod grab;
pub mod grace;
pub mod graft;
pub mod grapnel;
pub mod grapple;
pub mod grasp;
pub mod grave;
pub mod gravity;
pub mod graze;
pub mod greed;
pub mod grid_snap;
pub mod ground;
pub mod guard;
pub mod gust;
pub mod haste;
pub mod havoc;
pub mod haze;
pub mod health;
pub mod heat;
pub mod hew;
pub mod hex;
pub mod hitbox;
pub mod hobble;
pub mod hold;
pub mod homing;
pub mod hone;
pub mod horde;
pub mod hound;
pub mod hover;
pub mod hunger;
pub mod ignite;
pub mod imbue;
pub mod immune;
pub mod impact;
pub mod input_map;
pub mod interactable;
pub mod intercept;
pub mod interrupt;
pub mod inventory;
pub mod invincible;
pub mod isolate;
pub mod item;
pub mod jeer;
pub mod jetpack;
pub mod joint;
pub mod jolt;
pub mod jostle;
pub mod juke;
pub mod jump;
pub mod kinematic;
pub mod kneel;
pub mod knit;
pub mod knockback;
pub mod lacerate;
pub mod laden;
pub mod lament;
pub mod lance;
pub mod lapse;
pub mod lash;
pub mod latch;
pub mod layer;
pub mod ledge;
pub mod leech;
pub mod lens_flare;
pub mod level;
pub mod lifetime;
pub mod light;
pub mod lock;
pub mod lod;
pub mod logging;
pub mod loot_table;
pub mod lunge;
pub mod lure;
pub mod lurk;
pub mod magnet;
pub mod maim;
pub mod malice;
pub mod mana;
pub mod mark;
pub mod mass;
pub mod material;
pub mod melee;
pub mod mend;
pub mod merge;
pub mod mesh;
pub mod minimap;
pub mod mirage;
pub mod momentum;
pub mod morale;
pub mod morph;
pub mod motion_blur;
pub mod mount;
pub mod move_speed;
pub mod muffle;
pub mod name;
pub mod nav_mesh_agent;
pub mod network_id;
pub mod nimble;
pub mod notice;
pub mod nourish;
pub mod nova;
pub mod npc;
pub mod nullify;
pub mod numb;
pub mod obstacle;
pub mod omen;
pub mod orbit;
pub mod ordeal;
pub mod oscillate;
pub mod outlast;
pub mod outline;
pub mod overflow;
pub mod overheat;
pub mod overload;
pub mod overpower;
pub mod overshield;
pub mod parent;
pub mod parry;
pub mod particle_system;
pub mod patience;
pub mod patrol;
pub mod petrify;
pub mod phase;
pub mod pickup;
pub mod pierce;
pub mod pin;
pub mod pivot;
pub mod platform;
pub mod plea;
pub mod ploy;
pub mod pluck;
pub mod plunge;
pub mod poise;
pub mod poison;
pub mod portal;
pub mod pounce;
pub mod power;
pub mod projectile;
pub mod prone;
pub mod protect;
pub mod proud;
pub mod provoke;
pub mod prowl;
pub mod pulse;
pub mod quest;
pub mod radar;
pub mod ragdoll;
pub mod rage;
pub mod rally;
pub mod rampage;
pub mod ravage;
pub mod ray;
pub mod reave;
pub mod rebound;
pub mod recharge;
pub mod reckless;
pub mod recluse;
pub mod recoil;
pub mod reflect;
pub mod reflection_probe;
pub mod reflex;
pub mod regen;
pub mod repel;
pub mod repose;
pub mod respawn;
pub mod restitution;
pub mod retaliate;
pub mod reveal;
pub mod revenge;
pub mod reverb_zone;
pub mod revive;
pub mod ricochet;
pub mod rifle;
pub mod rigid_body;
pub mod root;
pub mod rope;
pub mod rot;
pub mod rout;
pub mod rupture;
pub mod save_data;
pub mod scald;
pub mod scan;
pub mod scar;
pub mod scatter;
pub mod scope;
pub mod scorch;
pub mod screen_shake;
pub mod sensor;
pub mod shadow;
pub mod shear;
pub mod shield;
pub mod shield_break;
pub mod shock;
pub mod shrivel;
pub mod shroud;
pub mod shunt;
pub mod silence;
pub mod siphon;
pub mod skeleton;
pub mod skinned_mesh;
pub mod skybox;
pub mod slam;
pub mod slay;
pub mod slide;
pub mod slime;
pub mod slink;
pub mod slow;
pub mod slow_mo;
pub mod smoke;
pub mod snare;
pub mod soak;
pub mod spawn_point;
pub mod spectral;
pub mod sphere;
pub mod spike;
pub mod splinter;
pub mod spring;
pub mod sprint;
pub mod sprite;
pub mod stagger;
pub mod stake;
pub mod stalk;
pub mod stamina;
pub mod stance;
pub mod stat;
pub mod status_effect;
pub mod stealth;
pub mod stomp;
pub mod stride;
pub mod strife;
pub mod stumble;
pub mod stun;
pub mod sulk;
pub mod sunder;
pub mod suppress;
pub mod surge;
pub mod surround;
pub mod survive;
pub mod swim;
pub mod tag;
pub mod taint;
pub mod tally;
pub mod talon;
pub mod taper;
pub mod target;
pub mod taunt;
pub mod tether;
pub mod text;
pub mod thaw;
pub mod thorns;
pub mod time;
pub mod timer;
pub mod tint;
pub mod tone_map;
pub mod trail;
pub mod trample;
pub mod trance;
pub mod tranquil;
pub mod transfix;
pub mod transform;
pub mod trap;
pub mod tremble;
pub mod tremor;
pub mod trigger;
pub mod trove;
pub mod turret;
pub mod tusk;
pub mod tween;
pub mod unrest;
pub mod upgrade;
pub mod upkeep;
pub mod urge;
pub mod velocity;
pub mod venom;
pub mod venture;
pub mod verge;
pub mod verve;
pub mod vest;
pub mod vex;
pub mod vibrate;
pub mod viewport;
pub mod vignette;
pub mod vigor;
pub mod vile;
pub mod visible;
pub mod vision;
pub mod void;
pub mod volumetric_light;
pub mod wall;
pub mod wane;
pub mod ward;
pub mod warn;
pub mod warp;
pub mod wart;
pub mod wary;
pub mod waste;
pub mod water_body;
pub mod wave;
pub mod wax;
pub mod weaken;
pub mod weal;
pub mod wear;
pub mod weasel;
pub mod weather;
pub mod weave;
pub mod web;
pub mod weed;
pub mod weft;
pub mod weld;
pub mod whelm;
pub mod whirl;
pub mod wilt;
pub mod wimp;
pub mod wince;
pub mod wind;
pub mod windup;
pub mod wine;
pub mod wink;
pub mod wire;
pub mod wisp;
pub mod wist;
pub mod witch;
pub mod wither;
pub mod wiz;
pub mod woe;
pub mod wok;
pub mod wolf;
pub mod woo;
pub mod worm;
pub mod worn;
pub mod wound;
pub mod wow;
pub mod wraith;
pub mod wrap;
pub mod wrath;
pub mod wreck;
pub mod wren;
pub mod wrest;
pub mod xray;
pub mod yak;
pub mod yam;
pub mod yang;
pub mod yank;
pub mod yap;
pub mod yard;
pub mod yare;
pub mod yarn;
pub mod yaw;
pub mod yawl;
pub mod yawn;
pub mod yawp;
pub mod yay;
pub mod yea;
pub mod year;
pub mod yearn;
pub mod yeast;
pub mod yell;
pub mod yelp;
pub mod yen;
pub mod yenta;
pub mod yeoman;
pub mod yep;
pub mod yes;
pub mod yeti;
pub mod yew;
pub mod yield_;
pub mod yikes;
pub mod yin;
pub mod yip;
pub mod yips;
pub mod yodel;
pub mod yoga;
pub mod yogi;
pub mod yoke;
pub mod yokel;
pub mod yolk;
pub mod yonder;
pub mod yore;
pub mod young;
pub mod yours;
pub mod youth;
pub mod yowl;
pub mod yoyo;
pub mod yuan;
pub mod yuck;
pub mod yuga;
pub mod yule;
pub mod yum;
pub mod yummy;
pub mod yup;
pub mod yurt;
pub mod z_index;
pub mod zafu;
pub mod zag;
pub mod zany;
pub mod zap;
pub mod zazen;
pub mod zeal;
pub mod zealot;
pub mod zebec;
pub mod zebra;
pub mod zebu;
pub mod zed;
pub mod zeitgeist;
pub mod zen;
pub mod zendo;
pub mod zenith;
pub mod zeolite;
pub mod zephyr;
pub mod zeppelin;
pub mod zerk;
pub mod zero;
pub mod zeroth;
pub mod zest;
pub mod zeugma;
pub mod zigzag;
pub mod zikr;
pub mod zilch;
pub mod zill;
pub mod zinc;
pub mod zing;
pub mod zinger;
pub mod zip;
pub mod zit;
pub mod zither;
pub mod ziti;
pub mod zloty;
pub mod zombie;
pub mod zone;
pub mod zoom;
pub mod zori;
pub mod zounds;
pub mod zulu;

pub use aabb::Aabb;
pub use ability::Ability;
pub use ability_slot::{AbilitySlot, Slot};
pub use absorption::Absorption;
pub use aggro::{Aggro, ThreatEntry};
pub use aim::{Aim, AimMode};
pub use alarm::Alarm;
pub use ambient_occlusion::AmbientOcclusion;
pub use ammo::Ammo;
pub use amplify::Amplify;
pub use anchor::{Anchor, AnchorPreset};
pub use angular_velocity::AngularVelocity;
pub use animation_player::AnimationPlayer;
pub use armor::{Armor, ArmorType};
pub use attach_point::AttachPoint;
pub use audio_emitter::{AudioEmitter, AudioListener};
pub use audio_filter::{AudioFilter, FilterType};
pub use aura::{Aura, AuraKind};
pub use avenge::Avenge;
pub use barrier::Barrier;
pub use beacon::Beacon;
pub use billboard::{Billboard, BillboardMode};
pub use blaze::Blaze;
pub use bleed::Bleed;
pub use blind::Blind;
pub use blink::{Blink, BlinkState};
pub use bloom::Bloom;
pub use bone::Bone;
pub use boon::Boon;
pub use boost::{Boost, BoostStat};
pub use breath::{Breath, BreathState};
pub use buff::{Buff, BuffEntry};
pub use bulk::Bulk;
pub use buoyancy::Buoyancy;
pub use burn::Burn;
pub use camera::Camera;
pub use camouflage::Camouflage;
pub use capsule::Capsule;
pub use carry::{Carry, CarryPhase};
pub use character_controller::CharacterController;
pub use charge::{Charge, ChargePhase};
pub use charm::Charm;
pub use chill::Chill;
pub use chromatic_aberration::ChromaticAberration;
pub use cinder::Cinder;
pub use climb::{Climb, ClimbPhase};
pub use cling::Cling;
pub use clip::{Clip, ClipState};
pub use cloth_body::ClothBody;
pub use collider::Collider;
pub use color::Color;
pub use color_grading::ColorGrading;
pub use combat::{Combat, CombatStance};
pub use combo::Combo;
pub use concuss::Concuss;
pub use confuse::Confuse;
pub use constraint::{Constraint, ConstraintKind};
pub use cooldown::Cooldown;
pub use corrosion::Corrosion;
pub use corrupt::Corrupt;
pub use counter::Counter;
pub use cover::Cover;
pub use cripple::Cripple;
pub use crosshair::{Crosshair, CrosshairStyle};
pub use crouch::{Crouch, CrouchPhase};
pub use crumble::Crumble;
pub use crunch::Crunch;
pub use crush::Crush;
pub use curse::{Curse, CurseKind};
pub use damage::{Damage, DamageType};
pub use damping::Damping;
pub use dash::{Dash, DashPhase};
pub use daze::Daze;
pub use debuff::{Debuff, DebuffEntry};
pub use decal::Decal;
pub use deflect::Deflect;
pub use demoralize::Demoralize;
pub use depth_of_field::DepthOfField;
pub use destructible::{Destructible, DestructionState};
pub use dialogue::{Dialogue, DialogueLine};
pub use disarm::Disarm;
pub use dissolve::Dissolve;
pub use dodge::{Dodge, DodgePhase};
pub use doom::Doom;
pub use door::{Door, DoorState};
pub use douse::Douse;
pub use drain::Drain;
pub use draw::{Draw, DrawPhase};
pub use dread::Dread;
pub use drench::Drench;
pub use echo::Echo;
pub use edge::Edge;
pub use emissive::Emissive;
pub use emote::{Emote, EmoteState};
pub use empower::Empower;
pub use enervate::Enervate;
pub use enlarge::Enlarge;
pub use entangle::Entangle;
pub use environment_map::EnvironmentMap;
pub use equip::{Equip, EquipSlot};
pub use exhaustion::Exhaustion;
pub use exile::Exile;
pub use experience::Experience;
pub use explosion::{Explosion, ExplosionState};
pub use expose::Expose;
pub use external_impulse::ExternalImpulse;
pub use faction::{Faction, FactionRel};
pub use fall::{Fall, FallState};
pub use faze::Faze;
pub use fear::{Fear, FearState};
pub use feint::Feint;
pub use fend::Fend;
pub use feral::Feral;
pub use fervor::Fervor;
pub use flare::Flare;
pub use flash::{Flash, FlashCurve};
pub use flinch::Flinch;
pub use flip_book::FlipBook;
pub use flow::Flow;
pub use fog::{Fog, FogMode};
pub use follow::{Follow, LookAt};
pub use footstep::{Footstep, SurfaceKind};
pub use force::{Force, ForceEntry, ForceMode};
pub use fracture::Fracture;
pub use freeze::{Freeze, FreezeState};
pub use friction::Friction;
pub use frostbite::Frostbite;
pub use fuel::{Fuel, FuelState};
pub use fury::Fury;
pub use fuse::Fuse;
pub use galvanize::Galvanize;
pub use ghost::{Ghost, GhostExitMode};
pub use glide::{Glide, GlidePhase};
pub use glimmer::Glimmer;
pub use glitch::Glitch;
pub use global_transform::GlobalTransform;
pub use goad::Goad;
pub use grab::{Grab, GrabRole};
pub use grace::Grace;
pub use graft::Graft;
pub use grapnel::{Grapnel, GrapnelState};
pub use grapple::{Grapple, GrappleState};
pub use grasp::Grasp;
pub use grave::Grave;
pub use gravity::{Gravity, GravityScale};
pub use graze::Graze;
pub use greed::Greed;
pub use grid_snap::GridSnap;
pub use ground::Ground;
pub use guard::{Guard, GuardPhase};
pub use gust::Gust;
pub use haste::{Haste, HasteKind, HasteStack};
pub use havoc::Havoc;
pub use haze::Haze;
pub use health::Health;
pub use heat::{Heat, ThermalState};
pub use hew::Hew;
pub use hex::Hex;
pub use hitbox::{Hitbox, HitboxShape};
pub use hobble::Hobble;
pub use hold::Hold;
pub use homing::{Homing, HomingMode};
pub use hone::Hone;
pub use horde::Horde;
pub use hound::Hound;
pub use hover::{Hover, HoverMode};
pub use hunger::{Hunger, HungerState};
pub use ignite::Ignite;
pub use imbue::Imbue;
pub use immune::Immune;
pub use impact::Impact;
pub use input_map::{Binding, InputCode, InputMap};
pub use interactable::{InteractTrigger, Interactable};
pub use intercept::Intercept;
pub use interrupt::Interrupt;
pub use inventory::Inventory;
pub use invincible::Invincible;
pub use isolate::Isolate;
pub use item::{Item, ItemCategory, ItemRarity};
pub use jeer::Jeer;
pub use jetpack::{Jetpack, JetpackState};
pub use joint::{Joint, JointType};
pub use jolt::Jolt;
pub use jostle::Jostle;
pub use juke::Juke;
pub use jump::Jump;
pub use kinematic::Kinematic;
pub use kneel::Kneel;
pub use knit::Knit;
pub use knockback::{Knockback, KnockbackSource};
pub use lacerate::Lacerate;
pub use laden::Laden;
pub use lament::Lament;
pub use lance::Lance;
pub use lapse::Lapse;
pub use lash::Lash;
pub use latch::Latch;
pub use layer::Layer;
pub use ledge::{Ledge, LedgePhase};
pub use leech::Leech;
pub use lens_flare::LensFlare;
pub use level::Level;
pub use lifetime::Lifetime;
pub use light::{DirectionalLight, PointLight, SpotLight};
pub use lock::{Lock, LockState};
pub use lod::{Lod, LodLevel};
pub use logging::init_logging;
pub use loot_table::{LootEntry, LootTable};
pub use lunge::{Lunge, LungePhase};
pub use lure::{Lure, LureState};
pub use lurk::Lurk;
pub use magnet::{Magnet, MagnetMode};
pub use maim::Maim;
pub use malice::Malice;
pub use mana::Mana;
pub use mark::{Mark, MarkEntry};
pub use mass::Mass;
pub use material::Material;
pub use melee::{Melee, MeleePhase};
pub use mend::Mend;
pub use merge::Merge;
pub use mesh::Mesh;
pub use minimap::Minimap;
pub use mirage::Mirage;
pub use momentum::Momentum;
pub use morale::Morale;
pub use morph::Morph;
pub use motion_blur::MotionBlur;
pub use mount::{Mount, SeatOffset};
pub use move_speed::MoveSpeed;
pub use muffle::Muffle;
pub use name::Name;
pub use nav_mesh_agent::{NavAgentState, NavMeshAgent};
pub use network_id::{NetworkAuthority, NetworkId};
pub use nimble::Nimble;
pub use notice::{Notice, NoticeState};
pub use nourish::Nourish;
pub use nova::Nova;
pub use npc::{Npc, NpcRole, NpcState};
pub use nullify::Nullify;
pub use numb::Numb;
pub use obstacle::{Obstacle, ObstacleShape};
pub use omen::Omen;
pub use orbit::Orbit;
pub use ordeal::Ordeal;
pub use oscillate::{Oscillate, OscillateAxis};
pub use outlast::Outlast;
pub use outline::{Outline, OutlineMode};
pub use overflow::Overflow;
pub use overheat::{Overheat, OverheatState};
pub use overload::Overload;
pub use overpower::Overpower;
pub use overshield::Overshield;
pub use parent::Parent;
pub use parry::{Parry, ParryState};
pub use particle_system::{EmissionShape, ParticleSystem};
pub use patience::Patience;
pub use patrol::{Patrol, PatrolMode};
pub use petrify::Petrify;
pub use phase::Phase;
pub use pickup::{Pickup, PickupEffect};
pub use pierce::Pierce;
pub use pin::Pin;
pub use pivot::{Pivot, PivotSpace};
pub use platform::{Platform, PlatformMode};
pub use plea::Plea;
pub use ploy::Ploy;
pub use pluck::Pluck;
pub use plunge::{Plunge, PlungePhase};
pub use poise::Poise;
pub use poison::Poison;
pub use portal::Portal;
pub use pounce::Pounce;
pub use power::{Power, PowerRole};
pub use projectile::Projectile;
pub use prone::Prone;
pub use protect::Protect;
pub use proud::Proud;
pub use provoke::Provoke;
pub use prowl::Prowl;
pub use pulse::{Pulse, PulseMode};
pub use quest::{Quest, QuestObjective, QuestState};
pub use radar::{Radar, RadarContact, RadarFilter};
pub use ragdoll::{Ragdoll, RagdollMode};
pub use rage::{Rage, RagePhase};
pub use rally::Rally;
pub use rampage::Rampage;
pub use ravage::Ravage;
pub use ray::Ray;
pub use reave::Reave;
pub use rebound::Rebound;
pub use recharge::Recharge;
pub use reckless::Reckless;
pub use recluse::Recluse;
pub use recoil::Recoil;
pub use reflect::Reflect;
pub use reflection_probe::{ProbeUpdateMode, ReflectionProbe};
pub use reflex::Reflex;
pub use regen::{Regen, RegenTarget};
pub use repel::Repel;
pub use repose::Repose;
pub use respawn::{Respawn, RespawnState};
pub use restitution::Restitution;
pub use retaliate::Retaliate;
pub use reveal::Reveal;
pub use revenge::Revenge;
pub use reverb_zone::ReverbZone;
pub use revive::{Revive, ReviveState};
pub use ricochet::Ricochet;
pub use rifle::Rifle;
pub use rigid_body::RigidBody;
pub use root::Root;
pub use rope::{Rope, RopeNode};
pub use rot::Rot;
pub use rout::Rout;
pub use rupture::Rupture;
pub use save_data::SaveData;
pub use scald::Scald;
pub use scan::Scan;
pub use scar::Scar;
pub use scatter::Scatter;
pub use scope::Scope;
pub use scorch::Scorch;
pub use screen_shake::ScreenShake;
pub use sensor::{Sensor, SensorShape};
pub use shadow::{Shadow, ShadowFilterMethod};
pub use shear::Shear;
pub use shield::Shield;
pub use shield_break::ShieldBreak;
pub use shock::Shock;
pub use shrivel::Shrivel;
pub use shroud::Shroud;
pub use shunt::Shunt;
pub use silence::Silence;
pub use siphon::Siphon;
pub use skeleton::Skeleton;
pub use skinned_mesh::SkinnedMesh;
pub use skybox::{Skybox, SkyboxProjection};
pub use slam::{Slam, SlamPhase};
pub use slay::Slay;
pub use slide::{Slide, SlidePhase};
pub use slime::Slime;
pub use slink::Slink;
pub use slow::Slow;
pub use slow_mo::{SlowMo, SlowMoSource};
pub use smoke::{Smoke, SmokeStyle};
pub use snare::Snare;
pub use soak::Soak;
pub use spawn_point::SpawnPoint;
pub use spectral::Spectral;
pub use sphere::Sphere;
pub use spike::Spike;
pub use splinter::Splinter;
pub use spring::Spring;
pub use sprint::{Sprint, SprintState};
pub use sprite::{Sprite, TextureAtlas};
pub use stagger::{Stagger, StaggerPhase};
pub use stake::Stake;
pub use stalk::Stalk;
pub use stamina::Stamina;
pub use stance::{Stance, StanceKind};
pub use stat::Stat;
pub use status_effect::{EffectKind, StatusEffect};
pub use stealth::{Stealth, Visibility};
pub use stomp::Stomp;
pub use stride::Stride;
pub use strife::Strife;
pub use stumble::Stumble;
pub use stun::{Stun, StunSeverity};
pub use sulk::Sulk;
pub use sunder::Sunder;
pub use suppress::Suppress;
pub use surge::Surge;
pub use surround::Surround;
pub use survive::Survive;
pub use swim::{Swim, SwimState};
pub use tag::Tag;
pub use taint::Taint;
pub use tally::Tally;
pub use talon::Talon;
pub use taper::Taper;
pub use target::{Target, TargetPriority};
pub use taunt::Taunt;
pub use tether::Tether;
pub use text::{Text, TextAlignment};
pub use thaw::Thaw;
pub use thorns::Thorns;
pub use time::Time;
pub use timer::Timer;
pub use tint::{Tint, TintMode};
pub use tone_map::{ToneMap, ToneMappingMode};
pub use trail::{Trail, TrailPoint};
pub use trample::Trample;
pub use trance::Trance;
pub use tranquil::Tranquil;
pub use transfix::Transfix;
pub use transform::Transform;
pub use trap::{Trap, TrapEffect, TrapState};
pub use tremble::Tremble;
pub use tremor::Tremor;
pub use trigger::{Trigger, TriggerEvent};
pub use trove::Trove;
pub use turret::{FireMode, Turret};
pub use tusk::Tusk;
pub use tween::{EasingFn, RepeatMode, Tween, TweenTarget};
pub use unrest::Unrest;
pub use upgrade::{Upgrade, UpgradeTier};
pub use upkeep::Upkeep;
pub use urge::Urge;
pub use velocity::Velocity;
pub use venom::Venom;
pub use venture::Venture;
pub use verge::Verge;
pub use verve::Verve;
pub use vest::Vest;
pub use vex::Vex;
pub use vibrate::Vibrate;
pub use viewport::Viewport;
pub use vignette::Vignette;
pub use vigor::Vigor;
pub use vile::Vile;
pub use visible::Visible;
pub use vision::Vision;
pub use void::Void;
pub use volumetric_light::VolumetricLight;
pub use wall::{Wall, WallState};
pub use wane::Wane;
pub use ward::Ward;
pub use warn::Warn;
pub use warp::{Warp, WarpPhase};
pub use wart::Wart;
pub use wary::Wary;
pub use waste::Waste;
pub use water_body::WaterBody;
pub use wave::Wave;
pub use wax::Wax;
pub use weaken::Weaken;
pub use weal::Weal;
pub use wear::Wear;
pub use weasel::Weasel;
pub use weather::{Precipitation, Weather};
pub use weave::Weave;
pub use web::Web;
pub use weed::Weed;
pub use weft::Weft;
pub use weld::Weld;
pub use whelm::Whelm;
pub use whirl::Whirl;
pub use wilt::Wilt;
pub use wimp::Wimp;
pub use wince::Wince;
pub use wind::Wind;
pub use windup::Windup;
pub use wine::Wine;
pub use wink::Wink;
pub use wire::Wire;
pub use wisp::Wisp;
pub use wist::Wist;
pub use witch::Witch;
pub use wither::Wither;
pub use wiz::Wiz;
pub use woe::Woe;
pub use wok::Wok;
pub use wolf::Wolf;
pub use woo::Woo;
pub use worm::Worm;
pub use worn::Worn;
pub use wound::Wound;
pub use wow::Wow;
pub use wraith::Wraith;
pub use wrap::Wrap;
pub use wrath::Wrath;
pub use wreck::Wreck;
pub use wren::Wren;
pub use wrest::Wrest;
pub use xray::Xray;
pub use yak::Yak;
pub use yam::Yam;
pub use yang::Yang;
pub use yank::Yank;
pub use yap::Yap;
pub use yard::Yard;
pub use yare::Yare;
pub use yarn::Yarn;
pub use yaw::Yaw;
pub use yawl::Yawl;
pub use yawn::Yawn;
pub use yawp::Yawp;
pub use yay::Yay;
pub use yea::Yea;
pub use year::Year;
pub use yearn::Yearn;
pub use yeast::Yeast;
pub use yell::Yell;
pub use yelp::Yelp;
pub use yen::Yen;
pub use yenta::Yenta;
pub use yeoman::Yeoman;
pub use yep::Yep;
pub use yes::Yes;
pub use yeti::Yeti;
pub use yew::Yew;
pub use yield_::Yield;
pub use yikes::Yikes;
pub use yin::Yin;
pub use yip::Yip;
pub use yips::Yips;
pub use yodel::Yodel;
pub use yoga::Yoga;
pub use yogi::Yogi;
pub use yoke::Yoke;
pub use yokel::Yokel;
pub use yolk::Yolk;
pub use yonder::Yonder;
pub use yore::Yore;
pub use young::Young;
pub use yours::Yours;
pub use youth::Youth;
pub use yowl::Yowl;
pub use yoyo::Yoyo;
pub use yuan::Yuan;
pub use yuck::Yuck;
pub use yuga::Yuga;
pub use yule::Yule;
pub use yum::Yum;
pub use yummy::Yummy;
pub use yup::Yup;
pub use yurt::Yurt;
pub use z_index::ZIndex;
pub use zafu::Zafu;
pub use zag::Zag;
pub use zany::Zany;
pub use zap::Zap;
pub use zazen::Zazen;
pub use zeal::Zeal;
pub use zealot::Zealot;
pub use zebec::Zebec;
pub use zebra::Zebra;
pub use zebu::Zebu;
pub use zed::Zed;
pub use zeitgeist::Zeitgeist;
pub use zen::Zen;
pub use zendo::Zendo;
pub use zenith::Zenith;
pub use zeolite::Zeolite;
pub use zephyr::Zephyr;
pub use zeppelin::Zeppelin;
pub use zerk::Zerk;
pub use zero::Zero;
pub use zeroth::Zeroth;
pub use zest::Zest;
pub use zeugma::Zeugma;
pub use zigzag::Zigzag;
pub use zikr::Zikr;
pub use zilch::Zilch;
pub use zill::Zill;
pub use zinc::Zinc;
pub use zing::Zing;
pub use zinger::Zinger;
pub use zip::Zip;
pub use zit::Zit;
pub use zither::Zither;
pub use ziti::Ziti;
pub use zloty::Zloty;
pub use zombie::Zombie;
pub use zone::Zone;
pub use zoom::Zoom;
pub use zori::Zori;
pub use zounds::Zounds;
pub use zulu::Zulu;

pub fn propagate_global_transforms(world: &mut bevy_ecs::world::World) {
    use bevy_ecs::prelude::Entity;
    use glam::Mat4;
    use std::collections::HashMap;

    let mut query = world.query::<(Entity, &Transform, Option<&Parent>)>();
    let entries: Vec<(Entity, Mat4, Option<Entity>)> = query
        .iter(world)
        .map(|(e, t, p)| (e, t.to_matrix(), p.map(|p| p.0)))
        .collect();

    let mut globals: HashMap<Entity, Mat4> =
        entries.iter().map(|(e, local, _)| (*e, *local)).collect();

    for _ in 0..8 {
        for (e, local, parent) in &entries {
            if let Some(parent_e) = parent {
                if let Some(&parent_global) = globals.get(parent_e) {
                    globals.insert(*e, parent_global * *local);
                }
            }
        }
    }

    let mut gt_query = world.query::<(Entity, &mut GlobalTransform)>();
    for (e, mut gt) in gt_query.iter_mut(world) {
        if let Some(&mat) = globals.get(&e) {
            gt.0 = mat;
        }
    }
}
