use bevy_ecs::prelude::Component;

/// Flagellate-spore dispersal tracker named after the zoospore (from
/// Greek zoion "animal" + spora "seed"), the motile asexual spore
/// produced by algae, water moulds, chytrids, and certain fungi. Unlike
/// the dust-like conidia of terrestrial moulds, zoospores are naked
/// cells — no cell wall, only a plasma membrane — that propel themselves
/// through water films or bulk liquid using one or two whiplash or
/// tinsel flagella. A typical Phytophthora zoospore is ten micrometres
/// long, swims at forty micrometres per second, and carries two
/// heterokont flagella: one directed forward to pull, one trailing to
/// steer. Once expelled from a sporangium into a puddle or the wet
/// surface of a leaf, it can detect gradients of isoflavones, amino
/// acids, or even electrical fields generated by plant wound sites;
/// it accumulates near the source, retracts its flagella, deposits a
/// cell wall, and germinates into a new mycelium within minutes. The
/// potato-blight organism Phytophthora infestans spreads through
/// zoospores released in rain; Batrachochytrium dendrobatidis, which
/// has driven dozens of amphibian species to extinction, disperses
/// identically through stream water. `motility` builds via
/// `propel(amount)` and accumulates passively at `swim_rate` per second
/// in `tick(dt)` or is consumed via `encyst(amount)`.
///
/// Models flagellate-spore dispersal fill levels, water-film swimming
/// saturation bars, chytrid-infection-spread accumulation trackers,
/// Phytophthora-dispersal risk gauges, aquatic-fungal-motility meters,
/// zoospore-release saturation indicators, mycelial-expansion range
/// fill levels, chemical-gradient-tracking accumulation bars, plant-
/// wound-site colonisation risk meters, or any mechanic where invisible
/// microscopic swimmers race through moisture films toward a target —
/// only to stop, wall themselves in, and explode into a new colony the
/// moment they reach it.
///
/// `propel(amount)` adds motility; fires `just_dispersed` when first
/// reaching `max_motility`. No-op when disabled.
///
/// `encyst(amount)` reduces motility immediately; fires `just_settled`
/// when reaching 0. No-op when disabled or already settled.
///
/// `tick(dt)` clears both flags, then increases motility by
/// `swim_rate * dt` (capped at `max_motility`). Fires `just_dispersed`
/// when first reaching max. No-op when disabled or rate is 0.
///
/// `is_dispersed()` returns `motility >= max_motility && enabled`.
///
/// `is_settled()` returns `motility == 0.0` (not gated by `enabled`).
///
/// `motility_fraction()` returns `(motility / max_motility).clamp(0, 1)`.
///
/// `effective_dispersal(scale)` returns `scale * motility_fraction()`
/// when enabled; `0.0` when disabled.
///
/// Default: `new(100.0, 1.5)` — swims at 1.5 units/sec.
#[derive(Component, Debug, Clone, PartialEq)]
pub struct Zoospore {
    pub motility: f32,
    pub max_motility: f32,
    pub swim_rate: f32,
    pub just_dispersed: bool,
    pub just_settled: bool,
    pub enabled: bool,
}

impl Zoospore {
    pub fn new(max_motility: f32, swim_rate: f32) -> Self {
        Self {
            motility: 0.0,
            max_motility: max_motility.max(0.1),
            swim_rate: swim_rate.max(0.0),
            just_dispersed: false,
            just_settled: false,
            enabled: true,
        }
    }

    /// Add motility; fires `just_dispersed` when first reaching max.
    /// No-op when disabled.
    pub fn propel(&mut self, amount: f32) {
        if !self.enabled || amount <= 0.0 {
            return;
        }
        let was_below = self.motility < self.max_motility;
        self.motility = (self.motility + amount).min(self.max_motility);
        if was_below && self.motility >= self.max_motility {
            self.just_dispersed = true;
        }
    }

    /// Reduce motility; fires `just_settled` when reaching 0.
    /// No-op when disabled or already settled.
    pub fn encyst(&mut self, amount: f32) {
        if !self.enabled || amount <= 0.0 || self.motility <= 0.0 {
            return;
        }
        self.motility = (self.motility - amount).max(0.0);
        if self.motility <= 0.0 {
            self.just_settled = true;
        }
    }

    /// Clear flags, then increase motility by `swim_rate * dt`.
    pub fn tick(&mut self, dt: f32) {
        self.just_dispersed = false;
        self.just_settled = false;
        if self.enabled && self.swim_rate > 0.0 && self.motility < self.max_motility {
            let was_below = self.motility < self.max_motility;
            self.motility = (self.motility + self.swim_rate * dt).min(self.max_motility);
            if was_below && self.motility >= self.max_motility {
                self.just_dispersed = true;
            }
        }
    }

    /// `true` when motility is at maximum and component is enabled.
    pub fn is_dispersed(&self) -> bool {
        self.motility >= self.max_motility && self.enabled
    }

    /// `true` when motility is 0 (not gated by `enabled`).
    pub fn is_settled(&self) -> bool {
        self.motility == 0.0
    }

    /// Fraction of maximum motility [0.0, 1.0].
    pub fn motility_fraction(&self) -> f32 {
        (self.motility / self.max_motility).clamp(0.0, 1.0)
    }

    /// Returns `scale * motility_fraction()` when enabled; `0.0` when disabled.
    pub fn effective_dispersal(&self, scale: f32) -> f32 {
        if !self.enabled {
            return 0.0;
        }
        scale * self.motility_fraction()
    }
}

impl Default for Zoospore {
    fn default() -> Self {
        Self::new(100.0, 1.5)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn z() -> Zoospore {
        Zoospore::new(100.0, 1.5)
    }

    // --- construction ---

    #[test]
    fn new_starts_settled() {
        let z = z();
        assert_eq!(z.motility, 0.0);
        assert!(z.is_settled());
        assert!(!z.is_dispersed());
    }

    #[test]
    fn new_clamps_max_motility() {
        let z = Zoospore::new(-5.0, 1.5);
        assert!((z.max_motility - 0.1).abs() < 1e-5);
    }

    #[test]
    fn new_clamps_swim_rate() {
        let z = Zoospore::new(100.0, -1.5);
        assert_eq!(z.swim_rate, 0.0);
    }

    #[test]
    fn default_values() {
        let z = Zoospore::default();
        assert!((z.max_motility - 100.0).abs() < 1e-5);
        assert!((z.swim_rate - 1.5).abs() < 1e-5);
    }

    // --- propel ---

    #[test]
    fn propel_adds_motility() {
        let mut z = z();
        z.propel(40.0);
        assert!((z.motility - 40.0).abs() < 1e-3);
    }

    #[test]
    fn propel_clamps_at_max() {
        let mut z = z();
        z.propel(200.0);
        assert!((z.motility - 100.0).abs() < 1e-3);
    }

    #[test]
    fn propel_fires_just_dispersed_at_max() {
        let mut z = z();
        z.propel(100.0);
        assert!(z.just_dispersed);
        assert!(z.is_dispersed());
    }

    #[test]
    fn propel_no_just_dispersed_when_already_at_max() {
        let mut z = z();
        z.motility = 100.0;
        z.propel(10.0);
        assert!(!z.just_dispersed);
    }

    #[test]
    fn propel_no_op_when_disabled() {
        let mut z = z();
        z.enabled = false;
        z.propel(50.0);
        assert_eq!(z.motility, 0.0);
    }

    #[test]
    fn propel_no_op_when_amount_zero() {
        let mut z = z();
        z.propel(0.0);
        assert_eq!(z.motility, 0.0);
    }

    // --- encyst ---

    #[test]
    fn encyst_reduces_motility() {
        let mut z = z();
        z.motility = 60.0;
        z.encyst(20.0);
        assert!((z.motility - 40.0).abs() < 1e-3);
    }

    #[test]
    fn encyst_clamps_at_zero() {
        let mut z = z();
        z.motility = 30.0;
        z.encyst(200.0);
        assert_eq!(z.motility, 0.0);
    }

    #[test]
    fn encyst_fires_just_settled_at_zero() {
        let mut z = z();
        z.motility = 30.0;
        z.encyst(30.0);
        assert!(z.just_settled);
    }

    #[test]
    fn encyst_no_op_when_already_settled() {
        let mut z = z();
        z.encyst(10.0);
        assert!(!z.just_settled);
    }

    #[test]
    fn encyst_no_op_when_disabled() {
        let mut z = z();
        z.motility = 50.0;
        z.enabled = false;
        z.encyst(50.0);
        assert!((z.motility - 50.0).abs() < 1e-3);
    }

    // --- tick ---

    #[test]
    fn tick_swims_motility() {
        let mut z = z(); // rate=1.5
        z.tick(4.0); // 0 + 1.5*4 = 6
        assert!((z.motility - 6.0).abs() < 1e-3);
    }

    #[test]
    fn tick_fires_just_dispersed_on_swim_to_max() {
        let mut z = Zoospore::new(100.0, 200.0);
        z.motility = 95.0;
        z.tick(1.0);
        assert!(z.just_dispersed);
        assert!(z.is_dispersed());
    }

    #[test]
    fn tick_no_swim_when_already_dispersed() {
        let mut z = z();
        z.motility = 100.0;
        z.tick(1.0);
        assert!(!z.just_dispersed);
    }

    #[test]
    fn tick_no_swim_when_rate_zero() {
        let mut z = Zoospore::new(100.0, 0.0);
        z.tick(100.0);
        assert_eq!(z.motility, 0.0);
    }

    #[test]
    fn tick_no_swim_when_disabled() {
        let mut z = z();
        z.enabled = false;
        z.tick(1.0);
        assert_eq!(z.motility, 0.0);
    }

    #[test]
    fn tick_clears_just_dispersed() {
        let mut z = Zoospore::new(100.0, 200.0);
        z.motility = 95.0;
        z.tick(1.0);
        z.tick(0.016);
        assert!(!z.just_dispersed);
    }

    #[test]
    fn tick_clears_just_settled() {
        let mut z = z();
        z.motility = 10.0;
        z.encyst(10.0);
        z.tick(0.016);
        assert!(!z.just_settled);
    }

    #[test]
    fn tick_scales_with_dt() {
        let mut z = z(); // rate=1.5
        z.tick(6.0); // 1.5*6 = 9
        assert!((z.motility - 9.0).abs() < 1e-3);
    }

    // --- is_dispersed / is_settled ---

    #[test]
    fn is_dispersed_false_when_disabled() {
        let mut z = z();
        z.motility = 100.0;
        z.enabled = false;
        assert!(!z.is_dispersed());
    }

    #[test]
    fn is_settled_not_gated_by_enabled() {
        let mut z = z();
        z.enabled = false;
        assert!(z.is_settled());
    }

    // --- motility_fraction / effective_dispersal ---

    #[test]
    fn motility_fraction_zero_when_settled() {
        assert_eq!(z().motility_fraction(), 0.0);
    }

    #[test]
    fn motility_fraction_half_at_midpoint() {
        let mut z = z();
        z.motility = 50.0;
        assert!((z.motility_fraction() - 0.5).abs() < 1e-4);
    }

    #[test]
    fn effective_dispersal_zero_when_settled() {
        assert_eq!(z().effective_dispersal(100.0), 0.0);
    }

    #[test]
    fn effective_dispersal_scales_with_motility() {
        let mut z = z();
        z.motility = 75.0;
        assert!((z.effective_dispersal(100.0) - 75.0).abs() < 1e-3);
    }

    #[test]
    fn effective_dispersal_zero_when_disabled() {
        let mut z = z();
        z.motility = 50.0;
        z.enabled = false;
        assert_eq!(z.effective_dispersal(100.0), 0.0);
    }
}
