use bevy_ecs::prelude::Component;

/// Facial-bone ossification tracker named after zygoma, the bony arch
/// formed where the zygomatic process of the temporal bone meets the
/// temporal process of the zygomatic (malar) bone to bridge the cheek
/// and temple on each side of the skull. The zygomatic arch is one of
/// the most prominent landmarks in comparative facial anatomy: it
/// projects laterally further than any other facial structure, houses
/// the masseter origin and insertion, and transmits the powerful bite
/// forces generated by the temporalis muscle passing beneath it through
/// the infratemporal fossa. In clinical terms the arch is vulnerable to
/// direct lateral impact — a zygomatic arch fracture is one of the most
/// common facial fractures — while in forensic and evolutionary biology
/// the size and flare of the zygoma is a reliable indicator of diet,
/// muscle mass, and taxonomic affinity. `arch` builds via
/// `reinforce(amount)` and accumulates passively at `ossify_rate` per
/// second in `tick(dt)` or is damaged via `fracture(amount)`.
///
/// Models facial-bone density fill levels, cheekbone structural-
/// integrity saturation bars, bite-force scaffold ossification trackers,
/// skeletal-stability accumulation gauges, forensic-anthropology
/// specimen-quality indicators, craniofacial-reconstruction progress
/// bars, impact-resistance bone-density saturation meters, skull-
/// scaffold reinforcement fill levels, dietary-hardness adaptation
/// trackers, or any mechanic where months of sustained mechanical load
/// slowly remodel and thicken a bony arch until it can sustain the kind
/// of forces that would snap an unreinforced structure — right up until
/// a poorly angled blow undoes in a millisecond what took a year of
/// chewing to build.
///
/// `reinforce(amount)` adds arch; fires `just_ossified` when first
/// reaching `max_arch`. No-op when disabled.
///
/// `fracture(amount)` reduces arch immediately; fires `just_fractured`
/// when reaching 0. No-op when disabled or already fractured.
///
/// `tick(dt)` clears both flags, then increases arch by
/// `ossify_rate * dt` (capped at `max_arch`). Fires `just_ossified`
/// when first reaching max. No-op when disabled or rate is 0.
///
/// `is_ossified()` returns `arch >= max_arch && enabled`.
///
/// `is_fractured()` returns `arch == 0.0` (not gated by `enabled`).
///
/// `arch_fraction()` returns `(arch / max_arch).clamp(0, 1)`.
///
/// `effective_structure(scale)` returns `scale * arch_fraction()`
/// when enabled; `0.0` when disabled.
///
/// Default: `new(100.0, 1.5)` — ossifies at 1.5 units/sec.
#[derive(Component, Debug, Clone, PartialEq)]
pub struct Zygoma {
    pub arch: f32,
    pub max_arch: f32,
    pub ossify_rate: f32,
    pub just_ossified: bool,
    pub just_fractured: bool,
    pub enabled: bool,
}

impl Zygoma {
    pub fn new(max_arch: f32, ossify_rate: f32) -> Self {
        Self {
            arch: 0.0,
            max_arch: max_arch.max(0.1),
            ossify_rate: ossify_rate.max(0.0),
            just_ossified: false,
            just_fractured: false,
            enabled: true,
        }
    }

    /// Add arch; fires `just_ossified` when first reaching max.
    /// No-op when disabled.
    pub fn reinforce(&mut self, amount: f32) {
        if !self.enabled || amount <= 0.0 {
            return;
        }
        let was_below = self.arch < self.max_arch;
        self.arch = (self.arch + amount).min(self.max_arch);
        if was_below && self.arch >= self.max_arch {
            self.just_ossified = true;
        }
    }

    /// Reduce arch; fires `just_fractured` when reaching 0.
    /// No-op when disabled or already fractured.
    pub fn fracture(&mut self, amount: f32) {
        if !self.enabled || amount <= 0.0 || self.arch <= 0.0 {
            return;
        }
        self.arch = (self.arch - amount).max(0.0);
        if self.arch <= 0.0 {
            self.just_fractured = true;
        }
    }

    /// Clear flags, then increase arch by `ossify_rate * dt`.
    pub fn tick(&mut self, dt: f32) {
        self.just_ossified = false;
        self.just_fractured = false;
        if self.enabled && self.ossify_rate > 0.0 && self.arch < self.max_arch {
            let was_below = self.arch < self.max_arch;
            self.arch = (self.arch + self.ossify_rate * dt).min(self.max_arch);
            if was_below && self.arch >= self.max_arch {
                self.just_ossified = true;
            }
        }
    }

    /// `true` when arch is at maximum and component is enabled.
    pub fn is_ossified(&self) -> bool {
        self.arch >= self.max_arch && self.enabled
    }

    /// `true` when arch is 0 (not gated by `enabled`).
    pub fn is_fractured(&self) -> bool {
        self.arch == 0.0
    }

    /// Fraction of maximum arch [0.0, 1.0].
    pub fn arch_fraction(&self) -> f32 {
        (self.arch / self.max_arch).clamp(0.0, 1.0)
    }

    /// Returns `scale * arch_fraction()` when enabled; `0.0` when disabled.
    pub fn effective_structure(&self, scale: f32) -> f32 {
        if !self.enabled {
            return 0.0;
        }
        scale * self.arch_fraction()
    }
}

impl Default for Zygoma {
    fn default() -> Self {
        Self::new(100.0, 1.5)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn z() -> Zygoma {
        Zygoma::new(100.0, 1.5)
    }

    // --- construction ---

    #[test]
    fn new_starts_fractured() {
        let z = z();
        assert_eq!(z.arch, 0.0);
        assert!(z.is_fractured());
        assert!(!z.is_ossified());
    }

    #[test]
    fn new_clamps_max_arch() {
        let z = Zygoma::new(-5.0, 1.5);
        assert!((z.max_arch - 0.1).abs() < 1e-5);
    }

    #[test]
    fn new_clamps_ossify_rate() {
        let z = Zygoma::new(100.0, -1.5);
        assert_eq!(z.ossify_rate, 0.0);
    }

    #[test]
    fn default_values() {
        let z = Zygoma::default();
        assert!((z.max_arch - 100.0).abs() < 1e-5);
        assert!((z.ossify_rate - 1.5).abs() < 1e-5);
    }

    // --- reinforce ---

    #[test]
    fn reinforce_adds_arch() {
        let mut z = z();
        z.reinforce(40.0);
        assert!((z.arch - 40.0).abs() < 1e-3);
    }

    #[test]
    fn reinforce_clamps_at_max() {
        let mut z = z();
        z.reinforce(200.0);
        assert!((z.arch - 100.0).abs() < 1e-3);
    }

    #[test]
    fn reinforce_fires_just_ossified_at_max() {
        let mut z = z();
        z.reinforce(100.0);
        assert!(z.just_ossified);
        assert!(z.is_ossified());
    }

    #[test]
    fn reinforce_no_just_ossified_when_already_at_max() {
        let mut z = z();
        z.arch = 100.0;
        z.reinforce(10.0);
        assert!(!z.just_ossified);
    }

    #[test]
    fn reinforce_no_op_when_disabled() {
        let mut z = z();
        z.enabled = false;
        z.reinforce(50.0);
        assert_eq!(z.arch, 0.0);
    }

    #[test]
    fn reinforce_no_op_when_amount_zero() {
        let mut z = z();
        z.reinforce(0.0);
        assert_eq!(z.arch, 0.0);
    }

    // --- fracture ---

    #[test]
    fn fracture_reduces_arch() {
        let mut z = z();
        z.arch = 60.0;
        z.fracture(20.0);
        assert!((z.arch - 40.0).abs() < 1e-3);
    }

    #[test]
    fn fracture_clamps_at_zero() {
        let mut z = z();
        z.arch = 30.0;
        z.fracture(200.0);
        assert_eq!(z.arch, 0.0);
    }

    #[test]
    fn fracture_fires_just_fractured_at_zero() {
        let mut z = z();
        z.arch = 30.0;
        z.fracture(30.0);
        assert!(z.just_fractured);
    }

    #[test]
    fn fracture_no_op_when_already_fractured() {
        let mut z = z();
        z.fracture(10.0);
        assert!(!z.just_fractured);
    }

    #[test]
    fn fracture_no_op_when_disabled() {
        let mut z = z();
        z.arch = 50.0;
        z.enabled = false;
        z.fracture(50.0);
        assert!((z.arch - 50.0).abs() < 1e-3);
    }

    // --- tick ---

    #[test]
    fn tick_ossifies_arch() {
        let mut z = z(); // rate=1.5
        z.tick(4.0); // 0 + 1.5*4 = 6
        assert!((z.arch - 6.0).abs() < 1e-3);
    }

    #[test]
    fn tick_fires_just_ossified_on_ossify_to_max() {
        let mut z = Zygoma::new(100.0, 200.0);
        z.arch = 95.0;
        z.tick(1.0);
        assert!(z.just_ossified);
        assert!(z.is_ossified());
    }

    #[test]
    fn tick_no_ossify_when_already_ossified() {
        let mut z = z();
        z.arch = 100.0;
        z.tick(1.0);
        assert!(!z.just_ossified);
    }

    #[test]
    fn tick_no_ossify_when_rate_zero() {
        let mut z = Zygoma::new(100.0, 0.0);
        z.tick(100.0);
        assert_eq!(z.arch, 0.0);
    }

    #[test]
    fn tick_no_ossify_when_disabled() {
        let mut z = z();
        z.enabled = false;
        z.tick(1.0);
        assert_eq!(z.arch, 0.0);
    }

    #[test]
    fn tick_clears_just_ossified() {
        let mut z = Zygoma::new(100.0, 200.0);
        z.arch = 95.0;
        z.tick(1.0);
        z.tick(0.016);
        assert!(!z.just_ossified);
    }

    #[test]
    fn tick_clears_just_fractured() {
        let mut z = z();
        z.arch = 10.0;
        z.fracture(10.0);
        z.tick(0.016);
        assert!(!z.just_fractured);
    }

    #[test]
    fn tick_scales_with_dt() {
        let mut z = z(); // rate=1.5
        z.tick(6.0); // 1.5*6 = 9
        assert!((z.arch - 9.0).abs() < 1e-3);
    }

    // --- is_ossified / is_fractured ---

    #[test]
    fn is_ossified_false_when_disabled() {
        let mut z = z();
        z.arch = 100.0;
        z.enabled = false;
        assert!(!z.is_ossified());
    }

    #[test]
    fn is_fractured_not_gated_by_enabled() {
        let mut z = z();
        z.enabled = false;
        assert!(z.is_fractured());
    }

    // --- arch_fraction / effective_structure ---

    #[test]
    fn arch_fraction_zero_when_fractured() {
        assert_eq!(z().arch_fraction(), 0.0);
    }

    #[test]
    fn arch_fraction_half_at_midpoint() {
        let mut z = z();
        z.arch = 50.0;
        assert!((z.arch_fraction() - 0.5).abs() < 1e-4);
    }

    #[test]
    fn effective_structure_zero_when_fractured() {
        assert_eq!(z().effective_structure(100.0), 0.0);
    }

    #[test]
    fn effective_structure_scales_with_arch() {
        let mut z = z();
        z.arch = 75.0;
        assert!((z.effective_structure(100.0) - 75.0).abs() < 1e-3);
    }

    #[test]
    fn effective_structure_zero_when_disabled() {
        let mut z = z();
        z.arch = 50.0;
        z.enabled = false;
        assert_eq!(z.effective_structure(100.0), 0.0);
    }
}
