[package]
name = "bsengine-asset"
description = "Asset loading — bevy_asset integration, LoadMode dispatch, texture assets"
version.workspace = true
edition.workspace = true

[dependencies]
bevy_app.workspace = true
bevy_ecs.workspace = true
bevy_asset.workspace = true
bevy_reflect.workspace = true
bevy_tasks.workspace = true
image.workspace = true

[dev-dependencies]
bsengine-app.workspace = true
