#!/usr/bin/env python3
"""Generates games/scale-level/assets/scenes/main.ron.

The level is too large to hand-author and too large to review as a diff, so
this generator is the source and the .ron is its committed output. Change the
counts below and re-run; never hand-edit the scene.

What the level holds, and why each part is there. Every count aims at a limit
the repo's own docs claim but nobody ever measured:

  PROPS   primitives with varied PBR materials -- per-object draw cost, the
          thing phase 1 measured in isolation
  FOXES   glTF skinned characters animating at once -- the comparison doc has
          said "CPU skinning is deliberately for 1~2 characters" since its
          first version, unmeasured
  POINTS  point lights, filling MAX_POINT_LIGHTS = 8 (surface.rs:6); each
          shadow-caster is a six-face cube render
  SPOTS   spot lights, filling MAX_SPOT_LIGHTS = 8 (surface.rs:7)

Set FOXES = 0 or POINTS = SPOTS = 0 and regenerate to isolate a cost. That is
the measurement this level exists for, not a debugging aid.
"""

from pathlib import Path

PROPS = 1200
FOXES = 20
POINTS = 8
SPOTS = 8

# Terrain: 4x4 chunks of 40 = 160x160, growing from the origin in the positive
# direction (it does not centre on it), so the middle is (80, _, 80).
CHUNKS = 4
CHUNK_SIZE = 40.0
SPAN = CHUNKS * CHUNK_SIZE
MID = SPAN / 2.0

# Kept inside the terrain with a margin, so nothing is placed off the edge
# where it would have no ground under it.
MARGIN = 8.0
LO, HI = MARGIN, SPAN - MARGIN

PRIMITIVES = ["Cube", "Sphere", "Plane", "Capsule", "Cylinder"]

OUT = Path(__file__).resolve().parents[1] / "games/scale-level/assets/scenes/main.ron"


def grid(n, i):
    """Deterministic (x, z) on a square grid across the terrain.

    No RNG: a run has to reproduce, and a level that differs between runs
    cannot be a measurement control.
    """
    side = max(1, int(n**0.5 + 0.999))
    ix, iz = i % side, i // side
    d = max(1, side - 1)
    return LO + (HI - LO) * ix / d, LO + (HI - LO) * iz / d


def main():
    out = []
    out.append(
        """// GENERATED by tools/gen_scale_level.py -- do not hand-edit.
//
// Re-run the generator after changing its counts. The generator's docstring
// explains what each group of entities is for; in short, every count aims at a
// limit the docs claim but nobody measured.
SceneDescriptor(entities: [
    EntityDescriptor(
        name: "Camera",
        camera: true,
        transform: Some((position: (%.1f, 30.0, %.1f))),
        look_at: Some((%.1f, 0.0, %.1f)),
    ),
    EntityDescriptor(
        name: "Sun",
        directional_light: Some((direction: (-0.4, -0.8, -0.3), color: (1.0, 0.97, 0.9), ambient: (0.22, 0.22, 0.26))),
    ),
    EntityDescriptor(
        name: "Ground",
        // The identity transform is load-bearing, not decoration: without an
        // explicit `transform:` the Terrain component generates no chunks and
        // no collider, and says nothing about it. A player dropped onto such a
        // terrain free-falls forever.
        transform: Some((position: (0.0, 0.0, 0.0))),
        components: [
            ("bsengine_scene::types::Terrain", "(heightmap_path: \\"assets/terrain/heightmap.png\\", chunk_count: (%d, %d), chunk_size: %.1f, height_scale: 8.0, layer0_texture_path: \\"assets/terrain/grass.png\\", layer1_texture_path: \\"assets/terrain/rock.png\\", layer2_texture_path: \\"assets/terrain/dirt.png\\", layer3_texture_path: \\"assets/terrain/snow.png\\", splatmap_path: None)"),
        ],
    ),
    EntityDescriptor(
        name: "Player",
        gltf: Some("assets/models/fox.glb"),
        transform: Some((position: (%.1f, 14.0, %.1f), scale: (0.02, 0.02, 0.02))),
        rigidbody: Some(Dynamic),
        collider: Some((shape: Capsule(half_height: 0.5, radius: 0.35), friction: 0.3)),
        script: Some("assets/scripts/player.js"),
        components: [
            ("bsengine_physics::components::CharacterBody", "(ground_check_distance: 0.2, max_slope_deg: 50.0, grounded: false)"),
        ],
    ),
"""
        % (MID, SPAN - 30.0, MID, MID, CHUNKS, CHUNKS, CHUNK_SIZE, MID, MID)
    )

    # Props. Materials vary where meshes cannot: the repo holds exactly one
    # mesh (fox.glb), so silhouette variety is not available and pretending
    # otherwise would spend effort on the wrong axis. The PBR path is real even
    # when the shapes repeat.
    for i in range(PROPS):
        x, z = grid(PROPS, i)
        prim = PRIMITIVES[i % len(PRIMITIVES)]
        r = (i % 7) / 7.0
        g = (i % 5) / 5.0
        b = (i % 3) / 3.0
        metallic = (i % 4) / 4.0
        rough = 0.15 + 0.8 * ((i % 6) / 6.0)
        y = 10.0 + (i % 3)
        out.append(
            f'    EntityDescriptor(name: "Prop{i}", primitive: Some({prim}), '
            f"transform: Some((position: ({x:.2f}, {y:.2f}, {z:.2f}))), "
            f"color: Some(({r:.2f}, {g:.2f}, {b:.2f})), "
            f'components: [("bsengine_core::material::Material", '
            f'"(base_color: ({r:.2f}, {g:.2f}, {b:.2f}), metallic: {metallic:.2f}, '
            f'roughness: {rough:.2f}, emissive: (0.0, 0.0, 0.0), opacity: 1.0)")]),\n'
        )

    # Foxes. Each carries fox.js so its clip actually plays -- a fox at rest is
    # skinned once and then costs nothing, so still foxes would measure nothing
    # at all, and the claim under test is about animating characters.
    for i in range(FOXES):
        x, z = grid(FOXES, i)
        out.append(
            f'    EntityDescriptor(name: "Fox{i}", gltf: Some("assets/models/fox.glb"), '
            f"transform: Some((position: ({x:.2f}, 6.0, {z:.2f}), scale: (0.02, 0.02, 0.02))), "
            f'script: Some("assets/scripts/fox.js")),\n'
        )

    # Lights, filling both caps. Point lights cast shadows as six-face cube
    # renders, which is the expensive part and the reason to fill the cap
    # rather than place a token few.
    for i in range(POINTS):
        x, z = grid(POINTS, i)
        out.append(
            f'    EntityDescriptor(name: "PointLight{i}", '
            f"transform: Some((position: ({x:.2f}, 12.0, {z:.2f}))), "
            f"point_light: Some((color: (1.0, 0.85, 0.7), intensity: 18.0, range: 45.0))),\n"
        )
    for i in range(SPOTS):
        x, z = grid(SPOTS, i)
        out.append(
            f'    EntityDescriptor(name: "SpotLight{i}", '
            f"transform: Some((position: ({x:.2f}, 20.0, {z:.2f}))), "
            f"spot_light: Some((color: (0.7, 0.85, 1.0), intensity: 22.0, range: 50.0, "
            f"inner_angle: 18.0, outer_angle: 32.0))),\n"
        )

    out.append("])\n")
    OUT.write_text("".join(out), encoding="utf-8", newline="\n")
    total = 4 + PROPS + FOXES + POINTS + SPOTS
    print(f"wrote {OUT} -- {total} entities "
          f"({PROPS} props, {FOXES} foxes, {POINTS} point + {SPOTS} spot lights)")


if __name__ == "__main__":
    main()
