cmake_minimum_required (VERSION 3.10)
project (@NAME@ NONE)
include (ExternalProject)

ExternalProject_Add (@NAME@
	GIT_REPOSITORY		@REPO@
	GIT_TAG				@TAG@
	GIT_SHALLOW			TRUE
	GIT_PROGRESS		TRUE
	SOURCE_DIR			@SRC_DIR@
	BINARY_DIR			@BUILD_DIR@
	CONFIGURE_COMMAND	""
	BUILD_COMMAND		""
	INSTALL_COMMAND		""
	TEST_COMMAND		""
)
