# Create defines based on PLATFORM
if (CMAKE_SYSTEM_NAME MATCHES "Windows") 
	set (PLATFORM_WINDOWS TRUE) 
elseif (CMAKE_SYSTEM_NAME MATCHES "Linux")
	set (PLATFORM_LINUX TRUE)
elseif (CMAKE_SYSTEM_NAME MATCHES "Darwin")
	set (PLATFORM_MAC TRUE)
endif ()

# Determine target ARCHitecture
if ((CMAKE_SYSTEM_PROCESSOR MATCHES "AMD64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "x86") AND CMAKE_SIZEOF_VOID_P EQUAL 8)
	set (ARCH_X64 TRUE)
elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "AMD64" AND CMAKE_SIZEOF_VOID_P EQUAL 4)
	set (ARCH_X86 TRUE)
endif ()

# Determine compiler
if (CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
	set (COMPILER_MSVC TRUE)
elseif (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
	set (COMPILER_CLANG TRUE)
elseif (CMAKE_CXX_COMPILER_ID MATCHES "GNU")
	set (COMPILER_GCC TRUE)
endif()