find_package (SDL2 CONFIG REQUIRED)
find_package (GLEW REQUIRED)
find_package (fmt CONFIG REQUIRED)
find_package (spdlog CONFIG REQUIRED)
find_package (rapidJSON CONFIG REQUIRED)
find_package (utf8cpp CONFIG REQUIRED)